version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Australia/Brisbane'
  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Australia/Brisbane'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
      timezone: 'Australia/Brisbane'